const fs = require('fs');
const c = fs.readFileSync('players-ucl.js', 'utf8');
eval(c);
console.log('Total:', STAR_PLAYERS_POOL.length);
console.log('\nTop 10 by rating:');
STAR_PLAYERS_POOL.sort((a,b) => b.rating - a.rating).slice(0,10).forEach(p => console.log(`  ${p.name} (${p.teamName}) - ${p.pos} - rating:${p.rating} val:${p.val}M`));
console.log('\nSample Arsenal:');
STAR_PLAYERS_POOL.filter(p => p.teamId === 'ars').slice(0,5).forEach(p => console.log(`  ${p.name} ${p.initials} - ${p.pos} rating:${p.rating} val:${p.val}M`));
console.log('\nPositions:', [...new Set(STAR_PLAYERS_POOL.map(p=>p.pos))].join(', '));
console.log('Teams:', new Set(STAR_PLAYERS_POOL.map(p=>p.teamId)).size);
