var DIRECT_QUALIFIED_TEAMS = [
{ id: "ars", name: "Arsenal", league: "UCL" },
{ id: "avl", name: "Aston Villa", league: "UCL" },
{ id: "liv", name: "Liverpool", league: "UCL" },
{ id: "mci", name: "Manchester City", league: "UCL" },
{ id: "mun", name: "Manchester United", league: "UCL" },
{ id: "bar", name: "Barcelona", league: "UCL" },
{ id: "rma", name: "Real Madrid", league: "UCL" },
{ id: "atm", name: "Atlético Madrid", league: "UCL" },
{ id: "vil", name: "Villarreal", league: "UCL" },
{ id: "bet", name: "Real Betis", league: "UCL" },
{ id: "int", name: "Inter Milan", league: "UCL" },
{ id: "nap", name: "Napoli", league: "UCL" },
{ id: "com", name: "Como", league: "UCL" },
{ id: "rom", name: "Roma", league: "UCL" },
{ id: "bay", name: "Bayern Munich", league: "UCL" },
{ id: "bvb", name: "Borussia Dortmund", league: "UCL" },
{ id: "rbl", name: "RB Leipzig", league: "UCL" },
{ id: "stu", name: "Stuttgart", league: "UCL" },
{ id: "psg", name: "Paris Saint-Germain", league: "UCL" },
{ id: "len", name: "RC Lens", league: "UCL" },
{ id: "lil", name: "Lille", league: "UCL" },
{ id: "psv", name: "PSV Eindhoven", league: "UCL" },
{ id: "fey", name: "Feyenoord", league: "UCL" },
{ id: "por", name: "Porto", league: "UCL" },
{ id: "scp", name: "Sporting CP", league: "UCL" },
{ id: "bru", name: "Club Brugge", league: "UCL" },
{ id: "sla", name: "SK Slavia Praha", league: "UCL" },
{ id: "gal", name: "Galatasaray", league: "UCL" },
{ id: "shd", name: "Shakhtar Donetsk", league: "UCL" }
];
