var DIRECT_QUALIFIED_TEAMS = [
{ id: "ars", name: "Arsenal", league: "UCL" },
{ id: "bay", name: "Bayern Munich", league: "UCL" },
{ id: "liv", name: "Liverpool", league: "UCL" },
{ id: "tot", name: "Tottenham Hotspur", league: "UCL" },
{ id: "bar", name: "Barcelona", league: "UCL" },
{ id: "che", name: "Chelsea", league: "UCL" },
{ id: "scp", name: "Sporting CP", league: "UCL" },
{ id: "mci", name: "Manchester City", league: "UCL" },
{ id: "rma", name: "Real Madrid", league: "UCL" },
{ id: "int", name: "Inter Milan", league: "UCL" },
{ id: "psg", name: "Paris Saint-Germain", league: "UCL" },
{ id: "new", name: "Newcastle United", league: "UCL" },
{ id: "juv", name: "Juventus", league: "UCL" },
{ id: "atm", name: "Atlético Madrid", league: "UCL" },
{ id: "ata", name: "Atalanta", league: "UCL" },
{ id: "lev", name: "Bayer Leverkusen", league: "UCL" },
{ id: "bvb", name: "Borussia Dortmund", league: "UCL" },
{ id: "oly", name: "Olympiacos", league: "UCL" },
{ id: "bru", name: "Club Brugge", league: "UCL" },
{ id: "gal", name: "Galatasaray", league: "UCL" },
{ id: "mon", name: "AS Monaco", league: "UCL" },
{ id: "qar", name: "Qarabag FK", league: "UCL" },
{ id: "bod", name: "Bodø/Glimt", league: "UCL" },
{ id: "ben", name: "Benfica", league: "UCL" },
{ id: "mar", name: "Olympique Marseille", league: "UCL" },
{ id: "paf", name: "Pafos FC", league: "UCL" },
{ id: "usg", name: "Royale Union SG", league: "UCL" },
{ id: "psv", name: "PSV Eindhoven", league: "UCL" },
{ id: "ath", name: "Athletic Club", league: "UCL" },
{ id: "nap", name: "Napoli", league: "UCL" },
{ id: "fck", name: "FC København", league: "UCL" },
{ id: "aja", name: "Ajax", league: "UCL" },
{ id: "sge", name: "Eintracht Frankfurt", league: "UCL" },
{ id: "sla", name: "SK Slavia Praha", league: "UCL" },
{ id: "vil", name: "Villarreal", league: "UCL" },
{ id: "kai", name: "Kairat Almaty", league: "UCL" }
];